import type {
  CEFRLevel,
  InterfaceLanguage,
  LanguagePair,
  TargetLanguage,
} from "@/types";

export const CEFR_LEVELS: CEFRLevel[] = [
  "A0",
  "A1",
  "A2",
  "B1",
  "B2",
  "C1",
];

export { LESSONS_PER_LEVEL, WORDS_PER_LESSON as VOCAB_PER_LESSON } from "@/data/curriculum/lessonCatalog";

export const LANGUAGE_PAIRS: {
  pair: LanguagePair;
  base: "ky" | "ru";
  target: TargetLanguage;
  labelKy: string;
  labelRu: string;
}[] = [
  {
    pair: "ky-de",
    base: "ky",
    target: "de",
    labelKy: "Кыргызча → Немисче",
    labelRu: "Кыргызский → Немецкий",
  },
  {
    pair: "ky-en",
    base: "ky",
    target: "en",
    labelKy: "Кыргызча → Англисче",
    labelRu: "Кыргызский → Английский",
  },
  {
    pair: "ru-de",
    base: "ru",
    target: "de",
    labelKy: "Орусча → Немисче",
    labelRu: "Русский → Немецкий",
  },
  {
    pair: "ru-en",
    base: "ru",
    target: "en",
    labelKy: "Орусча → Англисче",
    labelRu: "Русский → Английский",
  },
];

export const TARGET_LOCALES: Record<TargetLanguage, string> = {
  de: "de-DE",
  en: "en-US",
};

export const LEVEL_META: Record<
  CEFRLevel,
  { color: string; labelKy: string; labelRu: string }
> = {
  A0: {
    color: "from-emerald-400 to-teal-500",
    labelKy: "Абсолюттук башталгыч",
    labelRu: "Абсолютный новичок",
  },
  A1: {
    color: "from-sky-400 to-blue-500",
    labelKy: "Башталгыч",
    labelRu: "Начальный",
  },
  A2: {
    color: "from-violet-400 to-purple-500",
    labelKy: "Элементардык",
    labelRu: "Элементарный",
  },
  B1: {
    color: "from-amber-400 to-orange-500",
    labelKy: "Орто деңгээл",
    labelRu: "Средний",
  },
  B2: {
    color: "from-rose-400 to-pink-500",
    labelKy: "Жогорку орто",
    labelRu: "Выше среднего",
  },
  C1: {
    color: "from-fuchsia-400 to-purple-600",
    labelKy: "Өнүккөн",
    labelRu: "Продвинутый",
  },
};

export const UI_STRINGS: Record<
  InterfaceLanguage,
  Record<string, string>
> = {
  ky: {
    home: "Башкы бет",
    dictionary: "Сөздүк",
    profile: "Профиль",
    settings: "Жөндөөлөр",
    leaderboard: "Лигалар",
    signIn: "Кирүү",
    signUp: "Катталуу",
    logout: "Чыгуу",
    welcome: "Кош келиңиз",
    selectLevel: "Деңгээлди тандаңыз",
    lessons: "Сабактар",
    dailyStreak: "Күнүмдүк серия",
    wordsLearned: "Жатталган сөздөр",
    recentLessons: "Акыркы сабактар",
    search: "Издөө",
    voiceSearch: "Үн менен издөө",
    listen: "Угуу",
    editProfile: "Профилди түзөтүү",
    save: "Сактоо",
    cancel: "Жокко чыгаруу",
    notifications: "Эскертүүлөр",
    dailyReminders: "Күнүмдүк эскертүүлөр",
    achievementSounds: "Жетишкендик үндөрү",
    systemNotifications: "Системалык билдирүүлөр",
    preferences: "Тандоолор",
    interfaceLanguage: "Интерфейс тили",
    theme: "Тема",
    dark: "Караңгы",
    light: "Жарык",
    support: "Колдоо",
    help: "Жардам",
    faq: "Көп берилүүчү суроолор",
    contact: "Байланыш",
    progress: "Прогресс",
    minutes: "мүн",
    email: "Электрондук почта",
    password: "Сырсөз",
    name: "Аты",
    targetLanguage: "Максаттуу тил",
    noResults: "Эч нерсе табылган жок",
    translationKy: "Кыргызча",
    translationRu: "Орусча",
    lesson: "Сабак",
    vocabulary: "Сөздүк",
    readingGuide: "Окуу көрсөтмөсү",
    definition: "Аныктама",
    haveAccount: "Аккаунтуңуз барбы?",
    noAccount: "Аккаунтуңуз жокпу?",
    createAccount: "Аккаунт түзүү",
    loginTitle: "Кайра кош келиңиз",
    signupTitle: "Жаңы аккаунт түзүү",
    authSubtitle: "Немисче жана англисче үйрөнүңүз",
    back: "Артка",
    startQuiz: "Тестти баштоо",
    lessonComplete: "Сабак бүттү!",
    browseWords: "Бардык сөздөрдү караңыз",
    locked: "Кулптуу",
    quizProgress: "Тест прогресси",
    selectImage: "Туура сүрөттү тандаңыз",
    selectTranslation: "Туура котормону тандаңыз",
    visualMatch: "Сөздү сүрөт менен дал келтирүү",
    completionXp: "+50 XP алдыңыз!",
    returnHome: "Башкы бетке кайтуу",
    helpCenter: "Жардам борбору",
    contactUs: "Байланыш",
    uiFollowsPair: "Интерфейс тили тандалган тил жупуна жараша өзгөрөт",
    stageLabel: "Этап",
    stage1Title: "Сөздөр менен таанышуу",
    stage2Title: "Сүрөт жана аудио",
    stage3Title: "Сүйлөм курагыч",
    stage4Title: "Микрофон менен сүйлөө",
    stage5Title: "Жыйынтыктоочу тест",
    stage1Hint: "Жаңы сөз",
    stage2Hint: "Туура котормону тандаңыз",
    stage3Hint: "Сүйлөмдү куруңуз",
    stage4Hint: "Үнүңүз менен айтыңыз",
    stage5Hint: "Акыркы тест",
    nextWord: "Кийинки сөз",
    continueStage: "Кийинки этапка өтүү",
    tapChips: "Сөздөрдү тандаңыз...",
    sentenceCorrect: "Туура! Толук сүйлөм угулууда...",
    undo: "Артка",
    check: "Текшерүү",
    speakTarget: "Максат",
    listening: "Угулууда...",
    tapMic: "Микрофонду басыңыз",
    heard: "Угулду",
    tryAgain: "Кайра аракет кылыңыз",
    answerCorrect: "Туура!",
    answerIncorrect: "Туура эмес!",
    correctAnswerLabel: "Туура жооп",
    micDenied: "Микрофонго уруксат жок",
    skip: "Өткөрүп жиберүү",
    retry: "Кайра",
    speakingBonus: "+10 XP бонус үчүн туура айтыңыз",
    lessonAlreadyPassed: "Бул сабак бүткөрүлгөн",
    micInsecure: "Микрофон HTTPS же localhost аркылуу гана иштейт.",
    micUnsupported: "Браузер сүйлөөнү таанууну колдобойт.",
    submitSuggestion: "Сунуш киргизүү",
    suggestionPlaceholder: "Сайтка кошууга боло турган идеяңызды жазыңыз...",
    sendSuggestion: "Жөнөтүү",
    suggestionSent: "Рахмат! Сунушуңуз кабыл алынды.",
    adminDashboard: "Модератор панели",
    adminSubtitle: "Колдонуучулар жана сунуштар",
    userManagement: "Колдонуучулар",
    role: "Роль",
    actions: "Аракеттер",
    suggestionsInbox: "Сунуштар",
    noSuggestions: "Азырынча сунуш жок",
    adminPrivateArea: "Жашыруун админ зонасы",
    adminPrivateHint:
      "Бул бөлүм сизге гана көрүнөт. Колдонуучу ролдорун жана сунуштарды бул жерден башкарыңыз.",
    roleManagementHint: "USER жана MODERATOR ролдорун гана өзгөртө аласыз.",
    moderatorPanel: "Модератор Панели",
    userSuggestionsTitle: "Колдонуучулардын сунуштары",
    rootAdminPanel: "Башкы Администратор",
  },
  ru: {
    home: "Главная",
    dictionary: "Словарь",
    profile: "Профиль",
    settings: "Настройки",
    leaderboard: "Лиги",
    signIn: "Войти",
    signUp: "Регистрация",
    logout: "Выйти",
    welcome: "Добро пожаловать",
    selectLevel: "Выберите уровень",
    lessons: "Уроки",
    dailyStreak: "Ежедневная серия",
    wordsLearned: "Выучено слов",
    recentLessons: "Недавние уроки",
    search: "Поиск",
    voiceSearch: "Голосовой поиск",
    listen: "Слушать",
    editProfile: "Редактировать профиль",
    save: "Сохранить",
    cancel: "Отмена",
    notifications: "Уведомления",
    dailyReminders: "Ежедневные напоминания",
    achievementSounds: "Звуки достижений",
    systemNotifications: "Системные уведомления",
    preferences: "Настройки",
    interfaceLanguage: "Язык интерфейса",
    theme: "Тема",
    dark: "Тёмная",
    light: "Светлая",
    support: "Поддержка",
    help: "Помощь",
    faq: "Частые вопросы",
    contact: "Контакты",
    progress: "Прогресс",
    minutes: "мин",
    email: "Электронная почта",
    password: "Пароль",
    name: "Имя",
    targetLanguage: "Целевой язык",
    noResults: "Ничего не найдено",
    translationKy: "Кыргызский",
    translationRu: "Русский",
    lesson: "Урок",
    vocabulary: "Словарь",
    readingGuide: "Произношение",
    definition: "Определение",
    haveAccount: "Уже есть аккаунт?",
    noAccount: "Нет аккаунта?",
    createAccount: "Создать аккаунт",
    loginTitle: "С возвращением",
    signupTitle: "Создать аккаунт",
    authSubtitle: "Изучайте немецкий и английский",
    back: "Назад",
    startQuiz: "Начать тест",
    lessonComplete: "Урок завершён!",
    browseWords: "Просмотрите все слова",
    locked: "Заблокирован",
    quizProgress: "Прогресс теста",
    selectImage: "Выберите правильное изображение",
    selectTranslation: "Выберите правильный перевод",
    visualMatch: "Сопоставьте слово с картинкой",
    completionXp: "Вы получили +50 XP!",
    returnHome: "На главную",
    helpCenter: "Центр помощи",
    contactUs: "Контакты",
    uiFollowsPair: "Язык интерфейса следует за выбранной языковой парой",
    stageLabel: "Этап",
    stage1Title: "Знакомство со словами",
    stage2Title: "Картинка и аудио",
    stage3Title: "Конструктор предложений",
    stage4Title: "Говорение в микрофон",
    stage5Title: "Финальный тест",
    stage1Hint: "Новое слово",
    stage2Hint: "Выберите правильный перевод",
    stage3Hint: "Соберите предложение",
    stage4Hint: "Произнесите вслух",
    stage5Hint: "Финальный тест",
    nextWord: "Следующее слово",
    continueStage: "Перейти к следующему этапу",
    tapChips: "Нажимайте на слова...",
    sentenceCorrect: "Верно! Воспроизводится полное предложение...",
    undo: "Назад",
    check: "Проверить",
    speakTarget: "Цель",
    listening: "Слушаю...",
    tapMic: "Нажмите на микрофон",
    heard: "Распознано",
    tryAgain: "Попробуйте снова",
    answerCorrect: "Верно!",
    answerIncorrect: "Неверно!",
    correctAnswerLabel: "Правильный ответ",
    micDenied: "Нет доступа к микрофону",
    skip: "Пропустить",
    retry: "Повторить",
    speakingBonus: "+10 XP бонус за правильное произношение",
    lessonAlreadyPassed: "Этот урок уже пройден",
    micInsecure: "Микрофон работает только по HTTPS или на localhost.",
    micUnsupported: "Браузер не поддерживает распознавание речи.",
    submitSuggestion: "Предложить идею",
    suggestionPlaceholder: "Опишите идею или пожелание для сайта...",
    sendSuggestion: "Отправить",
    suggestionSent: "Спасибо! Ваше предложение получено.",
    adminDashboard: "Панель модератора",
    adminSubtitle: "Пользователи и предложения",
    userManagement: "Пользователи",
    role: "Роль",
    actions: "Действия",
    suggestionsInbox: "Предложения",
    noSuggestions: "Пока нет предложений",
    adminPrivateArea: "Приватная админ-зона",
    adminPrivateHint:
      "Этот раздел виден только вам. Управляйте ролями пользователей и просматривайте предложения здесь.",
    roleManagementHint: "Можно назначать только роли USER и MODERATOR.",
    moderatorPanel: "Панель модератора",
    userSuggestionsTitle: "Предложения пользователей",
    rootAdminPanel: "Главный администратор",
  },
};

export function getUiString(
  lang: InterfaceLanguage,
  key: string
): string {
  return UI_STRINGS[lang][key] ?? key;
}
